"""Loads the packaged consumer guide shipped with dbprint (SPEC 1.2.1).

Generated by scripts/gen_reading_guide.py, the source of truth; this module only reads it.
"""

from __future__ import annotations

import importlib.resources


READING_GUIDE_FILENAME = (
    "reading.md"  # lowercase: SPEC 1.5.1's path-segment allowlist is case-sensitive
)

READING_GUIDE_TEXT = (
    importlib.resources.files("dbprint.engine").joinpath("reading_guide.md").read_text()
)
