"""A generate run's writes, staged beside the print root and committed together with its manifest.

A commit marker lets the next run finish an interrupted commit; a stage without one is discarded.
"""

from __future__ import annotations

import json
import logging
import os
import shutil
import threading
from pathlib import Path
from typing import IO, Any

from .writer import validate_artifact_name, write_atomic


STAGE_DIRNAME = ".dbprint-run"
_MARKER = ".commit"
_MANIFEST = "manifest.yaml"

_LOG = logging.getLogger(__name__)


class StageRefused(RuntimeError):
    """Another run holds the connection's stage, or the stage and the print root are on two filesystems."""


class RunStage:
    """One run's staged writes and removals for one connection's print root."""

    def __init__(self, prints_root: Path, lock: IO[bytes]) -> None:
        self.prints_root = prints_root
        self.directory = prints_root.parent / STAGE_DIRNAME / prints_root.name
        self._lock = lock
        self._removals: dict[str, tuple[str, ...]] = {}
        self._mutex = threading.Lock()

    @classmethod
    def open(cls, prints_root: Path) -> RunStage:
        """Lock the connection, recover whatever an earlier run left, and start an empty stage."""

        root = prints_root.parent / STAGE_DIRNAME
        root.mkdir(parents=True, exist_ok=True)
        (root / ".gitignore").write_text("*\n", encoding="utf-8")
        lock = (root / f"{prints_root.name}.lock").open("ab")

        try:
            _lock(lock)
        except OSError as exc:
            lock.close()

            raise StageRefused(
                f"connection {prints_root.name!r} is being generated by another run; "
                f"wait for it to finish",
            ) from exc

        anchor = prints_root if prints_root.exists() else prints_root.parent

        if _device(root) != _device(anchor):
            lock.close()

            raise StageRefused(
                f"{str(root)!r} and {str(anchor)!r} are on different filesystems; generate "
                f"stages its writes beside the prints and needs both on one",
            )

        stage = cls(prints_root, lock)
        stage._recover()
        stage.directory.mkdir(parents=True)

        return stage

    def write(self, directory: Path, artifacts: dict[str, str | bytes]) -> None:
        """Stage `artifacts` for `directory`, a directory under the print root."""

        write_atomic(self.directory / directory.relative_to(self.prints_root), artifacts)

    def remove(self, directory: Path, names: tuple[str, ...]) -> None:
        """Record the named producer files of `directory` for deletion at commit."""

        for name in names:
            validate_artifact_name(name)

        with self._mutex:
            self._removals[directory.relative_to(self.prints_root).as_posix()] = names

    def commit(self) -> None:
        """Move every staged file into the print root, the manifest last, then apply removals."""

        staged = [
            p.relative_to(self.directory).as_posix()
            for p in self.directory.rglob("*")
            if p.is_file() and p.name != _MARKER
        ]
        writes = sorted(staged, key=_commit_order)
        removals = sorted(
            f"{directory}/{name}" for directory, names in self._removals.items() for name in names
        )
        marker = self.directory / _MARKER
        _write_synced(marker, json.dumps({"writes": writes, "removals": removals}))
        self._apply(writes, removals)
        shutil.rmtree(self.directory)

    def close(self) -> None:
        """Discard anything left uncommitted and release the lock; a failed discard only warns."""

        try:
            if self.directory.exists() and not (self.directory / _MARKER).exists():
                shutil.rmtree(self.directory)
        except OSError as exc:
            _LOG.warning("could not discard the stage %r: %s", str(self.directory), exc)
        finally:
            self._lock.close()

    def _recover(self) -> None:
        if not self.directory.exists():
            return

        marker = self.directory / _MARKER

        if marker.is_file():
            plan = json.loads(marker.read_text(encoding="utf-8"))
            self._apply(plan["writes"], plan["removals"])
            _LOG.warning(
                "connection %r: finished committing an interrupted run",
                self.prints_root.name,
            )
        else:
            tables = {p.parent for p in self.directory.rglob("*") if p.is_file()} - {self.directory}
            _LOG.warning(
                "connection %r: discarded an interrupted run's staged work (%d tables)",
                self.prints_root.name,
                len(tables),
            )

        shutil.rmtree(self.directory)

    def _apply(self, writes: list[str], removals: list[str]) -> None:
        for rel in [w for w in writes if w != _MANIFEST]:
            self._move(rel)

        for rel in removals:
            (self.prints_root / rel).unlink(missing_ok=True)

        for directory in sorted(
            {(self.prints_root / rel).parent for rel in removals},
            reverse=True,
        ):
            while (
                directory != self.prints_root
                and directory.is_dir()
                and not any(directory.iterdir())
            ):
                directory.rmdir()
                directory = directory.parent

        if _MANIFEST in writes:
            self._move(_MANIFEST)

    def _move(self, rel: str) -> None:
        staged = self.directory / rel

        if staged.is_file():
            final = self.prints_root / rel
            final.parent.mkdir(parents=True, exist_ok=True)
            os.replace(staged, final)


def _device(path: Path) -> int:
    return os.stat(path).st_dev


def _commit_order(rel: str) -> tuple[int, str]:
    if rel == _MANIFEST:
        return (2, rel)
    elif "/" not in rel:
        return (1, rel)
    else:
        return (0, rel)


def _write_synced(path: Path, text: str) -> None:
    tmp = path.with_name(path.name + ".tmp")

    with tmp.open("w", encoding="utf-8") as handle:
        handle.write(text)
        handle.flush()
        os.fsync(handle.fileno())

    os.replace(tmp, path)


def _lock(handle: Any) -> None:
    if os.name == "nt":
        import msvcrt

        msvcrt.locking(handle.fileno(), msvcrt.LK_NBLCK, 1)
    else:
        import fcntl

        fcntl.flock(handle.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
