"""The SPEC v1 section 2.2.3 field matrix, by classification - read by both the engine and the
validator. Only the flat rows live here; the conditional footnotes are derived by each reader.
"""

from __future__ import annotations


REQUIRED_FIELDS: dict[str, frozenset[str]] = {
    "boolean": frozenset(
        {
            "sql_type",
            "nullable",
            "null_count",
            "null_rate",
            "cardinality",
            "cardinality_ratio",
            "cardinality_method",
            "classification",
            "values",
            "values_coverage",
        },
    ),
    "json": frozenset(
        {
            "sql_type",
            "nullable",
            "null_count",
            "null_rate",
            "cardinality",
            "cardinality_ratio",
            "cardinality_method",
            "classification",
        },
    ),
    "composite": frozenset(
        {
            "sql_type",
            "nullable",
            "null_count",
            "null_rate",
            "classification",
            "parts",
            "parts_found",
        },
    ),
    "spatial": frozenset(
        {
            "sql_type",
            "nullable",
            "null_count",
            "null_rate",
            "classification",
            "geometry",
            "extent",
        },
    ),
    "vector": frozenset(
        {
            "sql_type",
            "nullable",
            "null_count",
            "null_rate",
            "classification",
            "dimension",
            "norm",
            "zero_count",
        },
    ),
    "foreign_key_candidate": frozenset(
        {
            "sql_type",
            "nullable",
            "null_count",
            "null_rate",
            "cardinality",
            "cardinality_ratio",
            "cardinality_method",
            "classification",
            "values",
            "values_coverage",
            "distribution",
            "length",
        },
    ),
    "categorical": frozenset(
        {
            "sql_type",
            "nullable",
            "null_count",
            "null_rate",
            "cardinality",
            "cardinality_ratio",
            "cardinality_method",
            "classification",
            "values",
            "values_coverage",
            "distribution",
            "length",
        },
    ),
    "temporal": frozenset(
        {
            "sql_type",
            "nullable",
            "null_count",
            "null_rate",
            "cardinality",
            "cardinality_ratio",
            "cardinality_method",
            "classification",
            "range",
            "percentiles",
            "freshness",
            "distribution",
            "frequencies",
            "values",
            "quantized_count",
        },
    ),
    "numeric": frozenset(
        {
            "sql_type",
            "nullable",
            "null_count",
            "null_rate",
            "cardinality",
            "cardinality_ratio",
            "cardinality_method",
            "classification",
            "range",
            "percentiles",
            "mean",
            "sum",
            "zero_count",
            "negative_count",
            "quantized_count",
            "distribution",
            "frequencies",
            "values",
        },
    ),
    "binary": frozenset(
        {
            "sql_type",
            "nullable",
            "null_count",
            "null_rate",
            "cardinality",
            "cardinality_ratio",
            "cardinality_method",
            "classification",
            "empty_count",
            "length",
        },
    ),
    "text": frozenset(
        {
            "sql_type",
            "nullable",
            "null_count",
            "null_rate",
            "cardinality",
            "cardinality_ratio",
            "cardinality_method",
            "classification",
            "values",
            "values_coverage",
            "empty_count",
            "distribution",
            "length",
        },
    ),
    "unsupported": frozenset({"sql_type", "nullable", "null_count", "null_rate", "classification"}),
}

FORBIDDEN_FIELDS: dict[str, frozenset[str]] = {
    "boolean": frozenset(
        {
            "types",
            "geometry",
            "extent",
            "dimension",
            "norm",
            "parts",
            "parts_found",
            "size",
            "occurrences",
            "distribution",
            "range",
            "percentiles",
            "mean",
            "sum",
            "zero_count",
            "negative_count",
            "empty_count",
            "quantized_count",
            "length",
            "normalized_cardinality",
            "freshness",
            "unrepresentable",
            "frequencies",
        },
    ),
    "json": frozenset(
        {
            "geometry",
            "extent",
            "dimension",
            "norm",
            "occurrences",
            "values",
            "values_coverage",
            "values_coverage_method",
            "distribution",
            "range",
            "percentiles",
            "mean",
            "sum",
            "zero_count",
            "negative_count",
            "empty_count",
            "quantized_count",
            "length",
            "normalized_cardinality",
            "freshness",
            "redacted",
            "unrepresentable",
            "frequencies",
            "sketch",
        },
    ),
    "composite": frozenset(
        {
            "types",
            "occurrences",
            "values",
            "values_coverage",
            "values_coverage_method",
            "distribution",
            "frequencies",
            "range",
            "percentiles",
            "mean",
            "sum",
            "negative_count",
            "quantized_count",
            "length",
            "normalized_cardinality",
            "freshness",
            "redacted",
            "unrepresentable",
            "sketch",
            "geometry",
            "extent",
            "dimension",
        },
    ),
    "spatial": frozenset(
        {
            "types",
            "dimension",
            "norm",
            "parts",
            "parts_found",
            "size",
            "occurrences",
            "cardinality",
            "cardinality_ratio",
            "cardinality_method",
            "values",
            "values_coverage",
            "values_coverage_method",
            "distribution",
            "range",
            "percentiles",
            "mean",
            "sum",
            "zero_count",
            "negative_count",
            "empty_count",
            "quantized_count",
            "length",
            "normalized_cardinality",
            "freshness",
            "unrepresentable",
            "frequencies",
            "sketch",
        },
    ),
    "vector": frozenset(
        {
            "types",
            "parts",
            "parts_found",
            "size",
            "occurrences",
            "geometry",
            "extent",
            "cardinality",
            "cardinality_ratio",
            "cardinality_method",
            "values",
            "values_coverage",
            "values_coverage_method",
            "distribution",
            "range",
            "percentiles",
            "mean",
            "sum",
            "negative_count",
            "empty_count",
            "quantized_count",
            "length",
            "normalized_cardinality",
            "freshness",
            "redacted",
            "unrepresentable",
            "frequencies",
            "sketch",
        },
    ),
    "foreign_key_candidate": frozenset(
        {
            "types",
            "geometry",
            "extent",
            "dimension",
            "norm",
            "parts",
            "parts_found",
            "size",
            "occurrences",
            "range",
            "percentiles",
            "mean",
            "sum",
            "zero_count",
            "negative_count",
            "empty_count",
            "quantized_count",
            "freshness",
            "unrepresentable",
            "frequencies",
        },
    ),
    "categorical": frozenset(
        {
            "types",
            "geometry",
            "extent",
            "dimension",
            "norm",
            "parts",
            "parts_found",
            "size",
            "occurrences",
            "range",
            "percentiles",
            "mean",
            "sum",
            "zero_count",
            "negative_count",
            "empty_count",
            "quantized_count",
            "freshness",
            "unrepresentable",
            "frequencies",
        },
    ),
    "temporal": frozenset(
        {
            "types",
            "geometry",
            "extent",
            "dimension",
            "norm",
            "parts",
            "parts_found",
            "size",
            "occurrences",
            "values_coverage",
            "values_coverage_method",
            "mean",
            "sum",
            "zero_count",
            "negative_count",
            "empty_count",
            "length",
            "normalized_cardinality",
        },
    ),
    "numeric": frozenset(
        {
            "types",
            "geometry",
            "extent",
            "dimension",
            "norm",
            "parts",
            "parts_found",
            "size",
            "occurrences",
            "values_coverage",
            "values_coverage_method",
            "freshness",
            "unrepresentable",
            "empty_count",
            "length",
            "normalized_cardinality",
        },
    ),
    "binary": frozenset(
        {
            "types",
            "geometry",
            "extent",
            "dimension",
            "norm",
            "parts",
            "parts_found",
            "size",
            "occurrences",
            "values",
            "values_coverage",
            "values_coverage_method",
            "distribution",
            "range",
            "percentiles",
            "mean",
            "sum",
            "zero_count",
            "negative_count",
            "quantized_count",
            "normalized_cardinality",
            "freshness",
            "unrepresentable",
            "frequencies",
        },
    ),
    "text": frozenset(
        {
            "types",
            "geometry",
            "extent",
            "dimension",
            "norm",
            "parts",
            "parts_found",
            "size",
            "occurrences",
            "range",
            "percentiles",
            "mean",
            "sum",
            "zero_count",
            "negative_count",
            "quantized_count",
            "freshness",
            "unrepresentable",
            "frequencies",
        },
    ),
    "unsupported": frozenset(
        {
            "types",
            "geometry",
            "extent",
            "dimension",
            "norm",
            "parts",
            "parts_found",
            "size",
            "occurrences",
            "cardinality",
            "cardinality_ratio",
            "cardinality_method",
            "values",
            "values_coverage",
            "values_coverage_method",
            "distribution",
            "range",
            "percentiles",
            "mean",
            "sum",
            "zero_count",
            "negative_count",
            "empty_count",
            "quantized_count",
            "length",
            "normalized_cardinality",
            "freshness",
            "inferred",
            "redacted",
            "unrepresentable",
            "frequencies",
            "sketch",
        },
    ),
}

# SPEC 2.2.18: a part has no catalog entry, join-key role or row population of its own.
PART_FORBIDDEN_FIELDS: frozenset[str] = frozenset(
    {
        "nullable",
        "physical_name",
        "collation",
        "physical_layout_key",
        "rows_scanned",
        "populated",
        "sketch",
        "normalized_cardinality",
        "parts",
        "parts_found",
    },
)


def part_required_fields(classification: str) -> frozenset[str]:
    """The fields a part of `classification` MUST carry: its column row, less the part delta."""

    return (REQUIRED_FIELDS.get(classification, frozenset()) - PART_FORBIDDEN_FIELDS) | {
        "occurrences",
    }


def part_forbidden_fields(classification: str) -> frozenset[str]:
    """The fields a part of `classification` MUST NOT carry: its column row plus the part delta."""

    return (FORBIDDEN_FIELDS.get(classification, frozenset()) - {"occurrences"}) | (
        PART_FORBIDDEN_FIELDS
    )


def forbids(classification: str | None, field: str) -> bool:
    """Whether SPEC 2.2.3's row for `classification` forbids `field`; an unknown one forbids nothing."""

    return field in FORBIDDEN_FIELDS.get(classification or "", frozenset())


def redactable_classifications() -> frozenset[str]:
    """The classifications whose row admits the `redacted` marker (SPEC 2.2.9)."""

    return frozenset(c for c in FORBIDDEN_FIELDS if not forbids(c, "redacted"))
